python classic2grid.py bin\Application tmp\Application
python classic2grid.py bin\Application1 tmp\Application1
python classic2grid.py bin\Connection tmp\Connection
python classic2grid.py bin\DemoWorld tmp\DemoWorld
python classic2grid.py bin\Scribble tmp\Scribble
python classic2grid.py bin\Server tmp\Server
python classic2grid.py bin\Storage tmp\Storage
python classic2grid.py bin\UserData tmp\UserData
python classic2grid.py bin\Vulture tmp\Vulture
python layoutgrid.py tmp\ApplicationLayout tmp\ApplicationLayout
python layoutgrid.py tmp\Application1Layout tmp\Application1Layout
python layoutgrid.py tmp\ConnectionLayout tmp\ConnectionLayout
python layoutgrid.py tmp\DemoWorldLayout tmp\DemoWorldLayout
python layoutgrid.py tmp\ScribbleLayout tmp\ScribbleLayout
python layoutgrid.py tmp\ServerLayout tmp\ServerLayout
python layoutgrid.py tmp\StorageLayout tmp\StorageLayout
python layoutgrid.py tmp\UserDataLayout tmp\UserDataLayout
python layoutgrid.py tmp\VultureLayout tmp\VultureLayout