import datetime, os, sys

if sys.platform == 'win32':
	hgcmd = 'hg id -i';
else:
	hgcmd = 'bash -l -c "hg id -i"';

buildversion = os.popen(hgcmd).read().strip() or 'unknown'
builddate = datetime.date.today().strftime('%Y%m%d')

f = open(os.path.normpath('src/BuildInfo.as'), 'w')
f.write('''\
/*
 * NOTE: This file was automatically generated by script/prebuild.py.
 * To regenerate it, run that script from the project's top-level folder.
 */



package BaseGame.Build
{
	public class BuildInfo
	{
		public static const DATE:String = "%s";
		public static const VERSION:String = "%s";
	}
}
''' % (builddate, buildversion))
f.close()
